[package]
name = "lib-voxels-application-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
url = { version = "2.5.4", features = ["serde"] }
mockall = "0.13.1"
uuid = { version = "1.16.0", features = ["v4", "serde"]}
